### PR TITLE
Release 0.1.2

### PR DESCRIPTION
**Pull request by justinvreeland**
Small fixes to documentation and build instructions.

### CODE REVIEW

**Comment by hirokazutakahashi** [comment]
Thanks for your patch.
Which distro does "uname -p" produces "unknown"?

**Comment by justinvreeland** [comment]
Off the top of my head Archlinux and Debian  I'm sure others do though.

**Comment by hirokazutakahashi** [comment]
Sorry for late reply. According to your comment, we applied another patches as 6ddcfd5e45bf7f902f0733ca50aa12cd12cb3bfd because we want to use "uname -p" for some dependency issues.  So could you resubmit your request only for 8208e170ffa339dcc1f0d0f3900a25d30ee499bc?

**Comment by justinvreeland** [comment]
Not a problem. I sent a new pull request you can find [here](https://github.com/lagopus/lagopus/pull/34). I'll close this one.

**Pull request closed without merging**
